task-tracker/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "tasks#index"
  get "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  resources :tasks, only: %i[index edit create update destroy]
  get "current", to: "tasks#current"
end

task-tracker/app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :description, presence: true
  enum status: { active: 0, completed: 1 }

  scope :for_popug, ->(id) { where(popug_id: id).order(created_at: :desc) }
end

task-tracker/app/controllers/application_controller.rb
# frozen_string_literal: true

require "jwt"

class ApplicationController < ActionController::Base
  private

  SSO_URL = "http://localhost:8080/sso/super-login/"
  JWT_SECRET = "POPUG_FOREVER_ULTIMATE_SECURE"

  def current_popug
    @current_popug ||= session[:popug]
  end

  def authenticate!
    return if current_popug

    if (popug = decode_popug_token)
      session[:popug] = popug
      redirect_to root_url
    else
      redirect_to login_url
    end
  end

  def decode_popug_token
    return nil unless params[:popug_token]

    JWT.decode(params[:popug_token], JWT_SECRET, "HS256").first
  end
end

task-tracker/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def login
    redirect_to root_path if current_popug

    @sso_url = SSO_URL
  end

  def logout
    reset_session
    redirect_to root_url
  end
end

task-tracker/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate!
  before_action :set_task, only: %i[edit update destroy]

  def index
    @tasks = Task.order(created_at: :desc)
    @new_task = Task.new
  end

  def current
    @tasks = Task.for_popug current_popug["id"]
  end

  def edit; end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url
    else
      redirect_to tasks_url, alert: task_errors
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url
    else
      flash.now.alert = task_errors
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_errors
    @task.errors.map(&:full_message).join
  end

  def task_params
    params.require(:task).permit(:description, :status)
  end
end

task-tracker/app/views/layouts/_header.html.erb
<div class="d-flex justify-content-between align-items-center mt-2 mb-4">
  <div class="fw-bold">PopugJira TaskTracker</div>
  <% if popug %>
    <div>
      <%= popug["name"] %>
      <%= image_tag popug["avatar"], size: "32", class: "rounded ms-2" %>
    </div>
  <% end %>
</div>

task-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopugJira TaskTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <style type="text/css">
      :root { --max-width: 600px; }
    </style>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header", popug: @current_popug %>
      <%= yield %>
    </div>
  </body>
</html>

task-tracker/app/views/tasks/_form.html.erb
<div style="max-width: var(--max-width);">
  <%= form_with(model: task, class: "d-flex") do |form| %>
    <div class="flex-grow-1">
      <%= form.text_field :description, class: "form-control w-100" %>
    </div>
    <div class="ms-2">
      <%= form.submit class: "btn btn-secondary" %>
    </div>
  <% end %>

  <div class="small" style="height: 1rem;"><%= alert %></div>
</div>

task-tracker/app/views/tasks/_task.html.erb
<div class="list-group-item d-flex justify-content-between">
  <div>
    <%= link_to(task_path(task, task: {status: task.completed? ? :active : :completed }),
                method: :patch, class: "text-decoration-none") do %>
      <input class="form-check-input" type="checkbox" <%= "checked" if task.completed? %> >
    <% end %>

    <%= link_to task.description, edit_task_path(task),
                class: "text-decoration-none #{"text-decoration-line-through" if task.completed?} text-reset" %>
  </div>

  <%= link_to "Delete", task, method: :delete, class: "link-secondary text-decoration-none" %>
</div>

task-tracker/app/views/tasks/current.html.erb
<h1 class="mb-2">My tasks</h1>

<div class="mb-4">
  <%= link_to "All tasks", tasks_path, class: "link-secondary text-decoration-none" %>
</div>

<div class="list-group mt-4" style="max-width: var(--max-width);">
  <%= @tasks.any? ? render(@tasks) : "No tasks yet" %>
</div>

task-tracker/app/views/tasks/edit.html.erb
<h1 class="mb-4">Editing Task</h1>

<%= render "form", task: @task %>

<div class="mt-4">
  <%= link_to "Back", tasks_path, class: "link-secondary text-decoration-none" %>
</div>

task-tracker/app/views/tasks/index.html.erb
<h1 class="mb-2">All tasks</h1>

<div class="mb-4">
  <%= link_to "My tasks", current_path, class: "link-secondary text-decoration-none" %>
</div>

<%= render "form", task: @new_task %>

<div class="list-group mt-4" style="max-width: var(--max-width);">
  <%= @tasks.any? ? render(@tasks) : "No tasks yet" %>
</div>